version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      # SQLite data directory inside container
      - DB_DIR=/data
      # Redis enabled by default
      - REDIS_URL=redis://redis:6379/0
      # Uvicorn
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
      - LOG_LEVEL=info
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: notification-net
