"""init schema

Revision ID: cbf668723ebe
Revises: 
Create Date: 2025-09-25 03:49:50.229476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cbf668723ebe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('tracking_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=256), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient'), 'notifications', ['recipient'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_tracking_id'), 'notifications', ['tracking_id'], unique=False)
    op.create_table('scheduled_notifications',
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('notification_data', sqlite.JSON(), nullable=False),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('recurrence', sa.String(length=128), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_scheduled_notifications_send_at'), 'scheduled_notifications', ['send_at'], unique=False)
    op.create_table('templates',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('variables', sqlite.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=True)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracking_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tracking_id'], ['notifications.tracking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_tracking_id'), 'delivery_attempts', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_attempts_tracking_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_scheduled_notifications_send_at'), table_name='scheduled_notifications')
    op.drop_table('scheduled_notifications')
    op.drop_index(op.f('ix_notifications_tracking_id'), table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient'), table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
